title: Ankit Chamaria
logo: assets/img/Photo_Ankit_Chamaria.png
description: I am currently pursuing a Master’s in Data Science, AI and ML from IIIT Bengaluru while actively managing my family business. With a strong foundation in strategic consulting, project management, and data-driven decision-making from my tenure at Boston Consulting Group, I am now focusing on applying AI to solve complex business problems.
show_downloads: true
theme: jekyll-theme-minimal
